# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init:  |
      pip install python-csv
      npm install -g json
      python -m pip install scipy  
      sudo apt-get install libsndfile1
      sudo pip3 install librosa
      sudo pip3 install streamlit
      sudo pip3 install streamlit-autorefresh
      sudo pip3 install matplotlib
      sudo pip3 install plotly_express
      sudo apt install -y mosquitto
      sudo apt install mosquitto-clients
      sudo service mosquitto start
      sudo service mosquitto status
      sudo pip3 install paho-mqtt
      git clone https://github.com/eclipse/paho.mqtt.python.git
      cd paho.mqtt.python
      python setup.py install
      cd ..
    command: streamlit run pagina.py
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  # default port?
  - port: 1883
    onOpen: ignore
    
  - port: 8501
    name: Web App
    description: Computer's Microphone Signal in Real Time
